<?php
$sugar_config_si  = array (
    'dbUSRData' => 'create',
    'default_currency_iso4217' => 'EUR',
    'default_currency_name' => 'Euro',
    'default_currency_significant_digits' => '2',
    'default_currency_symbol' => '€',
    'default_date_format' => 'd.m.Y',
    'default_decimal_seperator' => ',',
    'default_export_charset' => 'ISO-8859-1',
    'default_language' => 'de_de',
    'default_locale_name_format' => 's f l',
    'default_number_grouping_seperator' => '.',
    'default_time_format' => 'H:i',
    'export_delimiter' => ';',
    'setup_db_admin_password' => '{{password}}',
    'setup_db_admin_user_name' => '{{pac}}_{{user}}',
    'setup_db_create_database' => 0,
    'setup_db_database_name' => '{{pac}}_{{user}}',
    'setup_db_drop_tables' => 0,
    'setup_db_host_name' => 'localhost',
    'setup_db_pop_demo_data' => false,
    'setup_db_type' => 'mysql',
    'setup_db_username_is_privileged' => false,
    'setup_site_admin_password' => '{{AdminPassword}}',
    'setup_site_admin_user_name' => '{{AdminUsername}}',
    'setup_site_url' => 'https://{{domain}}',
    'setup_system_name' => '{{SiteName}}',
    'mail_smtpserver' => '{{pac}}.hostsharing.net',
    'mail_smtpport' => '4587',
    'mail_smtpssl' => 2,
    'mail_smtpauth_req' => 1,
    'mail_smtpuser' => '{{pac}}-{{user}}',
    'mail_smtppass' => '{{password}}',
    'notify_fromaddress' => 'do_not_reply@{{domain}}',
  );
?>